# Generated by Django 4.1.7 on 2023-03-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_genres_movie_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='films.genre'),
        ),
    ]
