# Generated by Django 4.1.7 on 2023-03-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_genre_delete_genres_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='films.genre'),
        ),
    ]
