# Generated by Django 4.1.7 on 2023-05-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_actor_comment_movie_avg_rating_movie_image_url_and_more'),
        ('films', '0009_alter_comment_rating'),
    ]

    operations = [
    ]
